title: Joseph Raczynski
tagline: Precision Engineered, Creatively Applied
description: Developer portfolio

url: "https://jraczynski6.github.io"
baseurl: ""

theme: jekyll-theme-merlot

markdown: kramdown

plugins:
  - jekyll-feed
